name: Audit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - name: Tap local checkout
        run: brew tap --custom-remote tenzir/homebrew-tenzir "$GITHUB_WORKSPACE"
      - name: Audit cask
        run: brew audit --cask --online --strict --tap=tenzir/homebrew-tenzir tenzir
